services:
  - type: web
    name: lirecouleur
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
